//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MARS_Config_dbEntities : DbContext
    {
        public MARS_Config_dbEntities()
			: base("name=MARS_Config_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mars_CCombinedEvents> mars_CCombinedEvents { get; set; }
        public virtual DbSet<mars_CEvents> mars_CEvents { get; set; }
        public virtual DbSet<mars_CGroupEvents> mars_CGroupEvents { get; set; }
        public virtual DbSet<mars_CGroups> mars_CGroups { get; set; }
        public virtual DbSet<mars_CRecordMarks> mars_CRecordMarks { get; set; }
        public virtual DbSet<mars_CRecords> mars_CRecords { get; set; }
        public virtual DbSet<mars_CSubEvents> mars_CSubEvents { get; set; }
    }
}
