//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CGroupEvents
    {
        public string GroupId { get; set; }
        public string EventId { get; set; }
        public string SubEventId { get; set; }
        public string Text { get; set; }
        public string Indoor { get; set; }
        public string Outdoor { get; set; }
    
        public virtual mars_CGroups mars_CGroups { get; set; }
        public virtual mars_CSubEvents mars_CSubEvents { get; set; }
    }
}
