//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CEvents
    {
        public mars_CEvents()
        {
            this.mars_CSubEvents = new HashSet<mars_CSubEvents>();
        }
    
        public string EventId { get; set; }
        public string Text { get; set; }
        public byte EventType { get; set; }
        public byte ResultPrecision { get; set; }
        public byte ResultLayout { get; set; }
        public int ManualTimeAdjustment { get; set; }
        public string WindMeasure { get; set; }
        public string WindMaxAllowed { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<mars_CSubEvents> mars_CSubEvents { get; set; }
    }
}
