//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CRecords
    {
        public mars_CRecords()
        {
            this.mars_CRecordMarks = new HashSet<mars_CRecordMarks>();
        }
    
        public string RecordId { get; set; }
        public string Text { get; set; }
        public string ShortText { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<mars_CRecordMarks> mars_CRecordMarks { get; set; }
    }
}
