//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CRecordMarks
    {
        public System.Guid RecordMarkId { get; set; }
        public string RecordId { get; set; }
        public string EventId { get; set; }
        public string SubEventId { get; set; }
        public string Name { get; set; }
        public string TeamName { get; set; }
        public string Place { get; set; }
        public string RecordDate { get; set; }
        public string Mark { get; set; }
        public string MarkAddOn { get; set; }
        public string MarkRemark { get; set; }
    
        public virtual mars_CRecords mars_CRecords { get; set; }
        public virtual mars_CSubEvents mars_CSubEvents { get; set; }
    }
}
