//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CCombinedEvents
    {
        public string CombinedEventId { get; set; }
        public string CombinedSubEventId { get; set; }
        public string EventId { get; set; }
        public string SubEventId { get; set; }
        public byte EventNo { get; set; }
        public byte DayNo { get; set; }
    
        public virtual mars_CSubEvents mars_CSubEvents { get; set; }
        public virtual mars_CSubEvents mars_CSubEvents1 { get; set; }
    }
}
