//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CGroups
    {
        public mars_CGroups()
        {
            this.mars_CGroupEvents = new HashSet<mars_CGroupEvents>();
        }
    
        public string GroupId { get; set; }
        public string Age { get; set; }
        public string Text { get; set; }
        public int SortKey { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<mars_CGroupEvents> mars_CGroupEvents { get; set; }
    }
}
