//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_CSubEvents
    {
        public mars_CSubEvents()
        {
            this.mars_CCombinedEvents = new HashSet<mars_CCombinedEvents>();
            this.mars_CCombinedEvents1 = new HashSet<mars_CCombinedEvents>();
            this.mars_CGroupEvents = new HashSet<mars_CGroupEvents>();
            this.mars_CRecordMarks = new HashSet<mars_CRecordMarks>();
        }
    
        public string EventId { get; set; }
        public string SubEventId { get; set; }
        public string Text { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<mars_CCombinedEvents> mars_CCombinedEvents { get; set; }
        public virtual ICollection<mars_CCombinedEvents> mars_CCombinedEvents1 { get; set; }
        public virtual mars_CEvents mars_CEvents { get; set; }
        public virtual ICollection<mars_CGroupEvents> mars_CGroupEvents { get; set; }
        public virtual ICollection<mars_CRecordMarks> mars_CRecordMarks { get; set; }
    }
}
