//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Meet
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_MTeams
    {
        public mars_MTeams()
        {
            this.mars_MParticipants = new HashSet<mars_MParticipants>();
        }
    
        public System.Guid MeetId { get; set; }
        public System.Guid TeamId { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Name3 { get; set; }
        public string Name6 { get; set; }
        public string Name9 { get; set; }
        public string Nation { get; set; }
        public string SortKey { get; set; }
        public string DAFName { get; set; }
        public Nullable<byte> UserDefined { get; set; }
    
        public virtual mars_MMeet mars_MMeet { get; set; }
        public virtual ICollection<mars_MParticipants> mars_MParticipants { get; set; }
    }
}
