//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Meet
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_MEventEntries
    {
        public mars_MEventEntries()
        {
            this.mars_MMarks = new HashSet<mars_MMarks>();
        }
    
        public System.Guid MeetId { get; set; }
        public System.Guid EventEntryId { get; set; }
        public string GroupId { get; set; }
        public string EventId { get; set; }
        public string SubEventId { get; set; }
        public string Text { get; set; }
        public string SubText { get; set; }
        public int SortKey { get; set; }
        public byte EventType { get; set; }
        public byte ResultPrecision { get; set; }
        public byte ResultLayout { get; set; }
        public int ManualTimeAdjustment { get; set; }
        public string WindMeasure { get; set; }
        public string WindMaxAllowed { get; set; }
        public byte RoundNo { get; set; }
        public byte HeatGroupNo { get; set; }
        public Nullable<byte> DayNo { get; set; }
        public Nullable<int> Seconds { get; set; }
        public string Indoor { get; set; }
        public string Outdoor { get; set; }
        public Nullable<byte> UserDefined { get; set; }
        public int SortKeyEventId { get; set; }
        public string RoundShorthand { get; set; }
        public string RoundText { get; set; }
        public Nullable<int> NoOfRounds { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Stopped { get; set; }
        public string LiveResults { get; set; }
        public string State { get; set; }
    
        public virtual mars_MGroups mars_MGroups { get; set; }
        public virtual ICollection<mars_MMarks> mars_MMarks { get; set; }
    }
}
