//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Meet
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_MParticipants
    {
        public mars_MParticipants()
        {
            this.mars_MMarks = new HashSet<mars_MMarks>();
        }
    
        public System.Guid MeetId { get; set; }
        public System.Guid ParticipantId { get; set; }
        public System.Guid TeamId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string FullName { get; set; }
        public string UsedName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Mail { get; set; }
        public string Alias { get; set; }
        public Nullable<int> DAFNo { get; set; }
        public Nullable<byte> UserDefined { get; set; }
        public Nullable<int> BibNo { get; set; }
    
        public virtual ICollection<mars_MMarks> mars_MMarks { get; set; }
        public virtual mars_MTeams mars_MTeams { get; set; }
    }
}
