//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Meet
{
    using System;
    using System.Collections.Generic;
    
    public partial class mars_MGroups
    {
        public mars_MGroups()
        {
            this.mars_MEventEntries = new HashSet<mars_MEventEntries>();
        }
    
        public System.Guid MeetId { get; set; }
        public string GroupId { get; set; }
        public string Age { get; set; }
        public string Text { get; set; }
        public int SortKey { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<mars_MEventEntries> mars_MEventEntries { get; set; }
        public virtual mars_MMeet mars_MMeet { get; set; }
    }
}
