//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.Meet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MARS_Meet_dbEntities : DbContext
    {
        public MARS_Meet_dbEntities()
            : base("name=MARS_Meet_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mars_MEventEntries> mars_MEventEntries { get; set; }
        public virtual DbSet<mars_MGroups> mars_MGroups { get; set; }
        public virtual DbSet<mars_MMarks> mars_MMarks { get; set; }
        public virtual DbSet<mars_MMeet> mars_MMeet { get; set; }
        public virtual DbSet<mars_MParticipants> mars_MParticipants { get; set; }
        public virtual DbSet<mars_MTeams> mars_MTeams { get; set; }
    }
}
